version: '3'
services:
  postgres:
    image: postgres:12.5-alpine
    ports:
    - '5432:5432'
    environment:
# Not required if POSTGRES_HOST_AUTH_METHOD is present
#      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: shiva
      POSTGRES_DB: postgres
    volumes:
    - ${PWD}/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
