CREATE TABLE students (
    roll_no BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(140) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    age SMALLINT NOT NULL 
);

INSERT INTO students VALUES (1, 'RAM', 'DELHI', '9455123451', 18);

